language: python
scala:
  - 2.11.12
jdk:
  - oraclejdk8
python:
  - 3.6
install:
  - mvn compile
  - pip install -r ./python/requirements.txt
env:
  - GIT_TAG = mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'

jobs:
  include:
    - stage: scala
      script:
        - ./scripts/scala_test.sh
    - stage: python
      script:
        - ./scripts/scala_deploy.sh
        - ./scripts/show_target.sh
        - ./scripts/python_test.sh

before_deploy:
  - git config --local user.name ${GIT_USR}
  - git config --local user.email ${GIT_EMAIL}
  - git tag ${GIT_TAG}

deploy:
  provider: script
  api_key: ${GITHUB_OAUTH}
  script: ./scripts/final_deploy.sh
  skip_cleanup: true
  file:
    - "target/*.jar"
    - "python/dist/*.tar.gz"
  on:
    branch: feature/deploy
    tags: true

notifications:
  email: false