jdk: oraclejdk8

cache:
  packages: true
  pip: true
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: scala
      language: java
      scala:
        - 2.11.12
      script:
        - ./scripts/scala_test.sh

    - stage: python
      language: python
      python:
        - 3.6
      install: pip install -r ./python/requirements.txt
      script:
        - ./scripts/scala_package.sh
        - ./scripts/show_target.sh
        - ./scripts/python_test.sh

    - stage: R
      language: r
      R:
        - 3.4.1
      before_install: cd ./R
      r_packages:
        - sparklyr
        - dplyr
        - here
      before_script: cd ..
      script:
        - ./scripts/scala_package.sh
        - ./scripts/show_target.sh
        - ./scripts/r_test.sh


notifications:
  email: false