language: python
scala:
  - 2.11.12
jdk:
  - oraclejdk8
python:
  - 3.6
install:
  - mvn dependency:resolve
  - pip install -r ./python/requirements.txt

script:
  - ./scripts/scala_test.sh
  - ./scripts/scala_deploy.sh
  - ./scripts/show_target.sh
  - ./scripts/python_test.sh
  - ./scripts/python_deploy.sh

notifications:
  email: false