language: python
scala:
  - 2.11.12
jdk:
  - oraclejdk8
python:
  - 3.6
install:
  - mvn compile
  - pip install -r ./python/requirements.txt

jobs:
  include:
    - stage: scala
      script: ./scripts/scala_test.sh
      after_success:
        - ./scripts/scala_deploy.sh
    - stage: python
      script:
        - ./scripts/show_target.sh
        - ./scripts/python_test.sh
      after_success:
        - ./scripts/python_deploy.sh

notifications:
  email: false