matrix:
  include:
    - language: scala
      scala:
        - 2.11.12
      jdk: oraclejdk8
      script:
        - ./scripts/scala_test.sh
      after_success:
        - ./scripts/scala_deploy.sh

    - language: python
      python:
        - 3.6
      install:
        - pip install -r ./python/requirements.txt
      script:
        - ./scripts/python_test.sh
      after_success:
        - ./scripts/python_deploy.sh


notifications:
  email: false