cache:
  packages: true
  pip: true
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: scala
      scala:
        - 2.11.12
      jdk: oraclejdk8
      script:
        - ./scripts/scala_test.sh

    - stage: python
      python:
        - 3.6
      jdk: oraclejdk8
      install: pip install -r ./python/requirements.txt
      script:
        - ./scripts/scala_deploy.sh
        - ./scripts/show_target.sh
        - ./scripts/python_test.sh

    - stage: R
      R:
        - 3.4.1
      script:
        - ./scripts/scala_deploy.sh
        - ./scripts/show_target.sh
        - ./scripts/r_test.sh


notifications:
  email: false