language: python
scala:
  - 2.11.12
jdk:
  - oraclejdk8
python:
  - 3.6
install:
  - pip install -r ./python/requirements.txt

jobs:
  include:
    - stage: scala test
      script: ./scripts/scala_test.sh
    - stage: scala deploy
      script: ./scripts/scala_deploy.sh
    - stage: python test
      script: ./scripts/python_test.sh
    - stage: python deploy
      script: ./scripts/python_deploy.sh

notifications:
  email: false