language: scala
scala:
  - 2.11.12
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: scala test
      script: ./scripts/scala_test.sh

    - stage: scala deploy
      script: ./scripts/scala_deploy.sh

    - stage: python test
      script: ./scripts/python_test.sh