language: python
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
scala:
  - 2.11.12
jdk:
  - oraclejdk8
python:
  - 3.6
install:
  - mvn compile
  - pip install -r ./python/requirements.txt

jobs:
  include:
    - stage: scala
      script:
        - ./scripts/scala_test.sh
    - stage: python
      script:
        - ./scripts/scala_deploy.sh
        - ./scripts/show_target.sh
        - ./scripts/python_test.sh

deploy:
  provider: script
  script: ./scripts/final_deploy.sh
  on:
    branch: master

notifications:
  email: false